language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - pip install git+git://github.com/lecnim/rucola.git@master
  - pip install markdown
  - pip install .
script: nosetests